// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, ig_user_id, handle, display_name, status, created_at, access_token, token_type, scopes, token_expires_at, token_refreshed_at FROM account WHERE id = $1
`

// Worker resolution: account_id (UUID, from task payload) → token + ig_user_id (ADR-002 §6.2).
func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.IgUserID,
		&i.Handle,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.AccessToken,
		&i.TokenType,
		&i.Scopes,
		&i.TokenExpiresAt,
		&i.TokenRefreshedAt,
	)
	return i, err
}

const getAccountByIgUserID = `-- name: GetAccountByIgUserID :one

SELECT id, ig_user_id, handle, display_name, status, created_at, access_token, token_type, scopes, token_expires_at, token_refreshed_at FROM account WHERE ig_user_id = $1
`

// Account + token store queries (ADR-002 §4.3). Token is the sole credential
// source per account — connect flow and refresh scheduler never persist it
// anywhere else (DRY §12a-1).
// Webhook resolution: entry.id (IGSID) → account row + token (ADR-002 §6.1).
func (q *Queries) GetAccountByIgUserID(ctx context.Context, igUserID string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIgUserID, igUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.IgUserID,
		&i.Handle,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.AccessToken,
		&i.TokenType,
		&i.Scopes,
		&i.TokenExpiresAt,
		&i.TokenRefreshedAt,
	)
	return i, err
}

const listAccountsDueForRefresh = `-- name: ListAccountsDueForRefresh :many
SELECT id, ig_user_id, handle, display_name, status, created_at, access_token, token_type, scopes, token_expires_at, token_refreshed_at FROM account
WHERE status = 'connected'
  AND token_expires_at IS NOT NULL
  AND token_expires_at < $1
ORDER BY token_expires_at ASC
`

// Refresh scheduler sweep: connected accounts whose token expires before
// @threshold (now + lead time, ADR-002 §5 step 1).
func (q *Queries) ListAccountsDueForRefresh(ctx context.Context, threshold pgtype.Timestamptz) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsDueForRefresh, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.IgUserID,
			&i.Handle,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.AccessToken,
			&i.TokenType,
			&i.Scopes,
			&i.TokenExpiresAt,
			&i.TokenRefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountExpired = `-- name: MarkAccountExpired :exec
UPDATE account SET status = 'expired' WHERE id = $1
`

// Refresh scheduler: refresh failed — mark the account expired rather than
// keep sending with a dead token (ADR-002 §5 step 2).
func (q *Queries) MarkAccountExpired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAccountExpired, id)
	return err
}

const updateAccountToken = `-- name: UpdateAccountToken :exec
UPDATE account
SET access_token       = $1,
    token_expires_at   = $2,
    token_refreshed_at = $3
WHERE id = $4
`

type UpdateAccountTokenParams struct {
	AccessToken      string             `json:"access_token"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
	TokenRefreshedAt pgtype.Timestamptz `json:"token_refreshed_at"`
	ID               pgtype.UUID        `json:"id"`
}

// Refresh scheduler: persist a successfully refreshed token (ADR-002 §5 step 2).
func (q *Queries) UpdateAccountToken(ctx context.Context, arg UpdateAccountTokenParams) error {
	_, err := q.db.Exec(ctx, updateAccountToken,
		arg.AccessToken,
		arg.TokenExpiresAt,
		arg.TokenRefreshedAt,
		arg.ID,
	)
	return err
}

const upsertAccountFromOAuth = `-- name: UpsertAccountFromOAuth :one
INSERT INTO account (
    ig_user_id,
    handle,
    display_name,
    access_token,
    token_type,
    scopes,
    token_expires_at,
    token_refreshed_at,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    now(),
    'connected'
)
ON CONFLICT (ig_user_id) DO UPDATE SET
    handle             = EXCLUDED.handle,
    display_name       = EXCLUDED.display_name,
    access_token       = EXCLUDED.access_token,
    token_type         = EXCLUDED.token_type,
    scopes             = EXCLUDED.scopes,
    token_expires_at   = EXCLUDED.token_expires_at,
    token_refreshed_at = now(),
    status             = 'connected'
RETURNING id, ig_user_id, handle, display_name, status, created_at, access_token, token_type, scopes, token_expires_at, token_refreshed_at
`

type UpsertAccountFromOAuthParams struct {
	IgUserID       string             `json:"ig_user_id"`
	Handle         string             `json:"handle"`
	DisplayName    string             `json:"display_name"`
	AccessToken    string             `json:"access_token"`
	TokenType      string             `json:"token_type"`
	Scopes         []string           `json:"scopes"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

// Connect callback: persist a freshly (re-)connected account. Re-connecting
// an existing ig_user_id refreshes its token and clears any prior 'expired' status.
func (q *Queries) UpsertAccountFromOAuth(ctx context.Context, arg UpsertAccountFromOAuthParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccountFromOAuth,
		arg.IgUserID,
		arg.Handle,
		arg.DisplayName,
		arg.AccessToken,
		arg.TokenType,
		arg.Scopes,
		arg.TokenExpiresAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.IgUserID,
		&i.Handle,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.AccessToken,
		&i.TokenType,
		&i.Scopes,
		&i.TokenExpiresAt,
		&i.TokenRefreshedAt,
	)
	return i, err
}
