// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :one
UPDATE app_user SET onboarding_completed_at = now() WHERE id = $1 RETURNING id, email, password_hash, segment, onboarding_completed_at, created_at
`

func (q *Queries) CompleteOnboarding(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, completeOnboarding, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Segment,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO app_user (email, password_hash) VALUES ($1, $2) RETURNING id, email, password_hash, segment, onboarding_completed_at, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

// app_user queries for the login + onboarding backend (ADR-003 §2.3).
// Handlers never write SQL directly — everything routes through
// apps/api/internal/auth/store.go (SoC §12a-3).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Segment,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, segment, onboarding_completed_at, created_at FROM app_user WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Segment,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, segment, onboarding_completed_at, created_at FROM app_user WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Segment,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setUserSegment = `-- name: SetUserSegment :one
UPDATE app_user SET segment = $1 WHERE id = $2 RETURNING id, email, password_hash, segment, onboarding_completed_at, created_at
`

type SetUserSegmentParams struct {
	Segment *string     `json:"segment"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserSegment(ctx context.Context, arg SetUserSegmentParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, setUserSegment, arg.Segment, arg.ID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Segment,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
