// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveCatalogPostByMedia = `-- name: GetActiveCatalogPostByMedia :one

SELECT id, account_id, ig_media_id, caption, comments_count, active, created_at FROM catalog_post
WHERE ig_media_id = $1
  AND account_id  = $2
  AND active      = true
`

type GetActiveCatalogPostByMediaParams struct {
	IgMediaID string      `json:"ig_media_id"`
	AccountID pgtype.UUID `json:"account_id"`
}

// Catalog and settings queries (ADR-001 §1.5, §4.4).
// Cheap ingest filter: confirm media is registered & active before enqueuing.
func (q *Queries) GetActiveCatalogPostByMedia(ctx context.Context, arg GetActiveCatalogPostByMediaParams) (CatalogPost, error) {
	row := q.db.QueryRow(ctx, getActiveCatalogPostByMedia, arg.IgMediaID, arg.AccountID)
	var i CatalogPost
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IgMediaID,
		&i.Caption,
		&i.CommentsCount,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCatalogPostByID = `-- name: GetCatalogPostByID :one
SELECT id, account_id, ig_media_id, caption, comments_count, active, created_at FROM catalog_post WHERE id = $1
`

func (q *Queries) GetCatalogPostByID(ctx context.Context, id pgtype.UUID) (CatalogPost, error) {
	row := q.db.QueryRow(ctx, getCatalogPostByID, id)
	var i CatalogPost
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IgMediaID,
		&i.Caption,
		&i.CommentsCount,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentOrderSettings = `-- name: GetCommentOrderSettings :one

SELECT account_id, keywords, hold_seconds, reply_template FROM comment_order_settings WHERE account_id = $1
`

// Settings: per-account keyword & hold config (§4.4).
func (q *Queries) GetCommentOrderSettings(ctx context.Context, accountID pgtype.UUID) (CommentOrderSetting, error) {
	row := q.db.QueryRow(ctx, getCommentOrderSettings, accountID)
	var i CommentOrderSetting
	err := row.Scan(
		&i.AccountID,
		&i.Keywords,
		&i.HoldSeconds,
		&i.ReplyTemplate,
	)
	return i, err
}

const listCatalogPostsByAccount = `-- name: ListCatalogPostsByAccount :many
SELECT id, account_id, ig_media_id, caption, comments_count, active, created_at FROM catalog_post
WHERE account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCatalogPostsByAccount(ctx context.Context, accountID pgtype.UUID) ([]CatalogPost, error) {
	rows, err := q.db.Query(ctx, listCatalogPostsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogPost{}
	for rows.Next() {
		var i CatalogPost
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.IgMediaID,
			&i.Caption,
			&i.CommentsCount,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogPost = `-- name: UpsertCatalogPost :one
INSERT INTO catalog_post (account_id, ig_media_id, caption, active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, ig_media_id) DO UPDATE SET
    caption = EXCLUDED.caption,
    active  = EXCLUDED.active
RETURNING id, account_id, ig_media_id, caption, comments_count, active, created_at
`

type UpsertCatalogPostParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	IgMediaID string      `json:"ig_media_id"`
	Caption   string      `json:"caption"`
	Active    bool        `json:"active"`
}

// Idempotent registration of a post/Reel for comment-to-order (used by
// cmd/seed; re-running never duplicates a row for the same account+media).
func (q *Queries) UpsertCatalogPost(ctx context.Context, arg UpsertCatalogPostParams) (CatalogPost, error) {
	row := q.db.QueryRow(ctx, upsertCatalogPost,
		arg.AccountID,
		arg.IgMediaID,
		arg.Caption,
		arg.Active,
	)
	var i CatalogPost
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IgMediaID,
		&i.Caption,
		&i.CommentsCount,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCommentOrderSettings = `-- name: UpsertCommentOrderSettings :one
INSERT INTO comment_order_settings (account_id, keywords, hold_seconds, reply_template)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id) DO UPDATE
    SET keywords       = EXCLUDED.keywords,
        hold_seconds   = EXCLUDED.hold_seconds,
        reply_template = EXCLUDED.reply_template
RETURNING account_id, keywords, hold_seconds, reply_template
`

type UpsertCommentOrderSettingsParams struct {
	AccountID     pgtype.UUID `json:"account_id"`
	Keywords      []string    `json:"keywords"`
	HoldSeconds   int32       `json:"hold_seconds"`
	ReplyTemplate string      `json:"reply_template"`
}

// Default keywords come from KIT_KEYWORDS.seller (packages/types/src/constants.ts).
// Keep both in sync when updating defaults.
func (q *Queries) UpsertCommentOrderSettings(ctx context.Context, arg UpsertCommentOrderSettingsParams) (CommentOrderSetting, error) {
	row := q.db.QueryRow(ctx, upsertCommentOrderSettings,
		arg.AccountID,
		arg.Keywords,
		arg.HoldSeconds,
		arg.ReplyTemplate,
	)
	var i CommentOrderSetting
	err := row.Scan(
		&i.AccountID,
		&i.Keywords,
		&i.HoldSeconds,
		&i.ReplyTemplate,
	)
	return i, err
}
