// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existsProcessedComment = `-- name: ExistsProcessedComment :one
SELECT EXISTS (
    SELECT 1 FROM processed_comment WHERE ig_comment_id = $1
)
`

// Read-check for enqueue-first ordering (ADR-007 §2.2 step 2): lets the webhook
// handler skip re-delivered events BEFORE attempting to enqueue, and catches
// Meta retries that arrive after the asynq TaskID Retention window has expired.
func (q *Queries) ExistsProcessedComment(ctx context.Context, igCommentID string) (bool, error) {
	row := q.db.QueryRow(ctx, existsProcessedComment, igCommentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertProcessedComment = `-- name: InsertProcessedComment :execrows

INSERT INTO processed_comment (
    ig_comment_id,
    account_id,
    ig_media_id,
    comment_text,
    contact_ig_user_id,
    contact_handle
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (ig_comment_id) DO NOTHING
`

type InsertProcessedCommentParams struct {
	IgCommentID     string      `json:"ig_comment_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	IgMediaID       string      `json:"ig_media_id"`
	CommentText     string      `json:"comment_text"`
	ContactIgUserID string      `json:"contact_ig_user_id"`
	ContactHandle   string      `json:"contact_handle"`
}

// Dedupe ledger for ingest (ADR-001 §3.2 step 3 / §8 — "Dedupe: dua lapis").
// InsertProcessedComment returns rows affected; caller checks == 0 → already processed.
func (q *Queries) InsertProcessedComment(ctx context.Context, arg InsertProcessedCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProcessedComment,
		arg.IgCommentID,
		arg.AccountID,
		arg.IgMediaID,
		arg.CommentText,
		arg.ContactIgUserID,
		arg.ContactHandle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
