// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commentorder_read.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommentOrderStats = `-- name: GetCommentOrderStats :one

SELECT
    COUNT(*)                                                        AS total_detected,
    COUNT(*) FILTER (WHERE status = 'reserved')                    AS reserved_now,
    COUNT(*) FILTER (WHERE status = 'waiting-pay')                 AS waiting_pay,
    COUNT(*) FILTER (WHERE status = 'closed-wa')                   AS closed_wa,
    COUNT(*) FILTER (WHERE status = 'expired-released')            AS expired_released
FROM reservation
WHERE catalog_post_id = $1
`

type GetCommentOrderStatsRow struct {
	TotalDetected   int64 `json:"total_detected"`
	ReservedNow     int64 `json:"reserved_now"`
	WaitingPay      int64 `json:"waiting_pay"`
	ClosedWa        int64 `json:"closed_wa"`
	ExpiredReleased int64 `json:"expired_released"`
}

// Aggregate read queries for the Comment-to-Order screen (ADR-001 §4.2).
// All queries keyed by catalog_post_id or account_id; designed for a single
// GET /api/v1/comment-order?accountId=&postId= handler that fans out these 4 queries.
// Counts by reservation status for the stats row (CommentOrderStatDTO).
// total_detected = total reservations ever created for this post (code-detected).
func (q *Queries) GetCommentOrderStats(ctx context.Context, catalogPostID pgtype.UUID) (GetCommentOrderStatsRow, error) {
	row := q.db.QueryRow(ctx, getCommentOrderStats, catalogPostID)
	var i GetCommentOrderStatsRow
	err := row.Scan(
		&i.TotalDetected,
		&i.ReservedNow,
		&i.WaitingPay,
		&i.ClosedWa,
		&i.ExpiredReleased,
	)
	return i, err
}

const getPostCommentCount = `-- name: GetPostCommentCount :one
SELECT comments_count FROM catalog_post WHERE id = $1
`

// For postCommentsLabel in CommentOrderResponse.
func (q *Queries) GetPostCommentCount(ctx context.Context, catalogPostID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostCommentCount, catalogPostID)
	var comments_count int32
	err := row.Scan(&comments_count)
	return comments_count, err
}

const listProductsByPost = `-- name: ListProductsByPost :many
SELECT
    code,
    name,
    price_idr,
    stock_left,
    stock_total
FROM product
WHERE catalog_post_id = $1
ORDER BY code
`

type ListProductsByPostRow struct {
	Code       string `json:"code"`
	Name       string `json:"name"`
	PriceIdr   int64  `json:"price_idr"`
	StockLeft  int32  `json:"stock_left"`
	StockTotal int32  `json:"stock_total"`
}

// Product list with live stock counters for the product panel (CatalogProductDTO).
func (q *Queries) ListProductsByPost(ctx context.Context, catalogPostID pgtype.UUID) ([]ListProductsByPostRow, error) {
	rows, err := q.db.Query(ctx, listProductsByPost, catalogPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByPostRow{}
	for rows.Next() {
		var i ListProductsByPostRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.PriceIdr,
			&i.StockLeft,
			&i.StockTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCommentsByPost = `-- name: ListRecentCommentsByPost :many
SELECT
    pc.ig_comment_id,
    pc.contact_handle,
    pc.comment_text,
    pc.received_at,
    r.code         AS matched_code,
    r.id           AS reservation_id,
    r.status       AS reservation_status
FROM processed_comment pc
LEFT JOIN reservation r ON r.ig_comment_id = pc.ig_comment_id
WHERE pc.account_id  = $1
  AND pc.ig_media_id = $2
ORDER BY pc.received_at DESC
LIMIT $3
`

type ListRecentCommentsByPostParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	IgMediaID string      `json:"ig_media_id"`
	Lim       int32       `json:"lim"`
}

type ListRecentCommentsByPostRow struct {
	IgCommentID       string             `json:"ig_comment_id"`
	ContactHandle     string             `json:"contact_handle"`
	CommentText       string             `json:"comment_text"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	MatchedCode       *string            `json:"matched_code"`
	ReservationID     pgtype.UUID        `json:"reservation_id"`
	ReservationStatus *ReservationStatus `json:"reservation_status"`
}

// Incoming comments for the left panel (IncomingCommentDTO).
// LEFT JOIN surfaces comments that were processed but did not match a code
// (matched_code IS NULL, reservation_id IS NULL).
func (q *Queries) ListRecentCommentsByPost(ctx context.Context, arg ListRecentCommentsByPostParams) ([]ListRecentCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listRecentCommentsByPost, arg.AccountID, arg.IgMediaID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentCommentsByPostRow{}
	for rows.Next() {
		var i ListRecentCommentsByPostRow
		if err := rows.Scan(
			&i.IgCommentID,
			&i.ContactHandle,
			&i.CommentText,
			&i.ReceivedAt,
			&i.MatchedCode,
			&i.ReservationID,
			&i.ReservationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByPostWithProduct = `-- name: ListReservationsByPostWithProduct :many
SELECT
    r.id,
    r.code,
    r.contact_handle,
    r.contact_ig_user_id,
    r.status,
    r.expires_at,
    r.closed_at,
    r.wa_link,
    r.reserved_at,
    p.name        AS product_name,
    p.price_idr   AS product_price_idr
FROM reservation r
JOIN product p ON p.id = r.product_id
WHERE r.catalog_post_id = $1
ORDER BY r.reserved_at DESC
LIMIT $3
OFFSET $2
`

type ListReservationsByPostWithProductParams struct {
	CatalogPostID pgtype.UUID `json:"catalog_post_id"`
	Off           int32       `json:"off"`
	Lim           int32       `json:"lim"`
}

type ListReservationsByPostWithProductRow struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	ContactHandle   string             `json:"contact_handle"`
	ContactIgUserID string             `json:"contact_ig_user_id"`
	Status          ReservationStatus  `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	WaLink          string             `json:"wa_link"`
	ReservedAt      pgtype.Timestamptz `json:"reserved_at"`
	ProductName     string             `json:"product_name"`
	ProductPriceIdr int64              `json:"product_price_idr"`
}

// Reservation rows with product context for the reservation panel (ReservationDTO).
func (q *Queries) ListReservationsByPostWithProduct(ctx context.Context, arg ListReservationsByPostWithProductParams) ([]ListReservationsByPostWithProductRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByPostWithProduct, arg.CatalogPostID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReservationsByPostWithProductRow{}
	for rows.Next() {
		var i ListReservationsByPostWithProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ContactHandle,
			&i.ContactIgUserID,
			&i.Status,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.WaLink,
			&i.ReservedAt,
			&i.ProductName,
			&i.ProductPriceIdr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
