// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConversation = `-- name: GetConversation :one
SELECT id, account_id, contact_ig_user_id, last_interaction_at, last_source, created_at, updated_at FROM conversation WHERE account_id = $1 AND contact_ig_user_id = $2
`

type GetConversationParams struct {
	AccountID       pgtype.UUID `json:"account_id"`
	ContactIgUserID string      `json:"contact_ig_user_id"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.AccountID, arg.ContactIgUserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactIgUserID,
		&i.LastInteractionAt,
		&i.LastSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversationInteraction = `-- name: UpsertConversationInteraction :one

INSERT INTO conversation (account_id, contact_ig_user_id, last_interaction_at, last_source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, contact_ig_user_id) DO UPDATE SET
    last_interaction_at = GREATEST(conversation.last_interaction_at, EXCLUDED.last_interaction_at),
    last_source         = EXCLUDED.last_source,
    updated_at          = now()
RETURNING id, account_id, contact_ig_user_id, last_interaction_at, last_source, created_at, updated_at
`

type UpsertConversationInteractionParams struct {
	AccountID         pgtype.UUID        `json:"account_id"`
	ContactIgUserID   string             `json:"contact_ig_user_id"`
	LastInteractionAt pgtype.Timestamptz `json:"last_interaction_at"`
	LastSource        string             `json:"last_source"`
}

// Window/last-interaction store (ADR-006 §4.2/§5.3). Postgres, not Redis — the
// 24h messaging window is compliance-critical state (§4c), not a fana counter.
// Buka/refresh window. GREATEST menjaga monoton bila event tiba out-of-order.
func (q *Queries) UpsertConversationInteraction(ctx context.Context, arg UpsertConversationInteractionParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, upsertConversationInteraction,
		arg.AccountID,
		arg.ContactIgUserID,
		arg.LastInteractionAt,
		arg.LastSource,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ContactIgUserID,
		&i.LastInteractionAt,
		&i.LastSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
