// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertProcessedMessage = `-- name: InsertProcessedMessage :execrows

INSERT INTO processed_message (ig_message_id, account_id, subtype, contact_ig_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ig_message_id) DO NOTHING
`

type InsertProcessedMessageParams struct {
	IgMessageID     string      `json:"ig_message_id"`
	AccountID       pgtype.UUID `json:"account_id"`
	Subtype         string      `json:"subtype"`
	ContactIgUserID string      `json:"contact_ig_user_id"`
}

// Dedupe ledger for messaging ingest (ADR-006 §5.4, mirror comments.sql).
// 0 rows → sudah pernah diproses (dedupe). Pola sama InsertProcessedComment.
func (q *Queries) InsertProcessedMessage(ctx context.Context, arg InsertProcessedMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProcessedMessage,
		arg.IgMessageID,
		arg.AccountID,
		arg.Subtype,
		arg.ContactIgUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
