// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ReservationStatus string

const (
	ReservationStatusReserved        ReservationStatus = "reserved"
	ReservationStatusWaitingPay      ReservationStatus = "waiting-pay"
	ReservationStatusClosedWa        ReservationStatus = "closed-wa"
	ReservationStatusExpiredReleased ReservationStatus = "expired-released"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

func (e ReservationStatus) Valid() bool {
	switch e {
	case ReservationStatusReserved,
		ReservationStatusWaitingPay,
		ReservationStatusClosedWa,
		ReservationStatusExpiredReleased:
		return true
	}
	return false
}

func AllReservationStatusValues() []ReservationStatus {
	return []ReservationStatus{
		ReservationStatusReserved,
		ReservationStatusWaitingPay,
		ReservationStatusClosedWa,
		ReservationStatusExpiredReleased,
	}
}

type Account struct {
	ID               pgtype.UUID        `json:"id"`
	IgUserID         string             `json:"ig_user_id"`
	Handle           string             `json:"handle"`
	DisplayName      string             `json:"display_name"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AccessToken      string             `json:"access_token"`
	TokenType        string             `json:"token_type"`
	Scopes           []string           `json:"scopes"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
	TokenRefreshedAt pgtype.Timestamptz `json:"token_refreshed_at"`
	UserID           pgtype.UUID        `json:"user_id"`
}

type AppUser struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	Segment               *string            `json:"segment"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type CatalogPost struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	IgMediaID     string             `json:"ig_media_id"`
	Caption       string             `json:"caption"`
	CommentsCount int32              `json:"comments_count"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CommentOrderSetting struct {
	AccountID     pgtype.UUID `json:"account_id"`
	Keywords      []string    `json:"keywords"`
	HoldSeconds   int32       `json:"hold_seconds"`
	ReplyTemplate string      `json:"reply_template"`
}

type OutboundLog struct {
	ID           pgtype.UUID        `json:"id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	Kind         string             `json:"kind"`
	TargetUserID string             `json:"target_user_id"`
	TriggerKey   string             `json:"trigger_key"`
	IgObjectID   string             `json:"ig_object_id"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

type ProcessedComment struct {
	IgCommentID     string             `json:"ig_comment_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	IgMediaID       string             `json:"ig_media_id"`
	CommentText     string             `json:"comment_text"`
	ContactIgUserID string             `json:"contact_ig_user_id"`
	ContactHandle   string             `json:"contact_handle"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

type Product struct {
	ID            pgtype.UUID `json:"id"`
	CatalogPostID pgtype.UUID `json:"catalog_post_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	PriceIdr      int64       `json:"price_idr"`
	StockTotal    int32       `json:"stock_total"`
	StockLeft     int32       `json:"stock_left"`
}

type Reservation struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CatalogPostID   pgtype.UUID        `json:"catalog_post_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Code            string             `json:"code"`
	IgCommentID     string             `json:"ig_comment_id"`
	ContactIgUserID string             `json:"contact_ig_user_id"`
	ContactHandle   string             `json:"contact_handle"`
	Status          ReservationStatus  `json:"status"`
	HoldSeconds     int32              `json:"hold_seconds"`
	ReservedAt      pgtype.Timestamptz `json:"reserved_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	WaLink          string             `json:"wa_link"`
}

type UserSession struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
