// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementStock = `-- name: DecrementStock :one
UPDATE product
SET stock_left = stock_left - 1
WHERE id         = $1
  AND stock_left > 0
RETURNING id, catalog_post_id, code, name, price_idr, stock_total, stock_left
`

// Atomically claim one unit. Returns the updated row; returns no rows if stock_left = 0.
// Caller treats zero rows as "out of stock" — do NOT create a reservation in that case.
func (q *Queries) DecrementStock(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, decrementStock, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CatalogPostID,
		&i.Code,
		&i.Name,
		&i.PriceIdr,
		&i.StockTotal,
		&i.StockLeft,
	)
	return i, err
}

const getProductByPostAndCode = `-- name: GetProductByPostAndCode :one

SELECT id, catalog_post_id, code, name, price_idr, stock_total, stock_left FROM product
WHERE catalog_post_id = $1
  AND code            = $2
`

type GetProductByPostAndCodeParams struct {
	CatalogPostID pgtype.UUID `json:"catalog_post_id"`
	Code          string      `json:"code"`
}

// Stock management queries for comment-to-order (ADR-001 §1.5).
// DecrementStock and IncrementStock are single-UPDATE atomic guards —
// the WHERE condition prevents oversell and double-release (§10 concurrency).
func (q *Queries) GetProductByPostAndCode(ctx context.Context, arg GetProductByPostAndCodeParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByPostAndCode, arg.CatalogPostID, arg.Code)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CatalogPostID,
		&i.Code,
		&i.Name,
		&i.PriceIdr,
		&i.StockTotal,
		&i.StockLeft,
	)
	return i, err
}

const incrementStock = `-- name: IncrementStock :one
UPDATE product
SET stock_left = LEAST(stock_left + 1, stock_total)
WHERE id = $1
RETURNING id, catalog_post_id, code, name, price_idr, stock_total, stock_left
`

// Atomically release one unit (auto-release on expire). Guards against exceeding
// stock_total via LEAST so a double-release still yields a consistent state.
func (q *Queries) IncrementStock(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, incrementStock, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CatalogPostID,
		&i.Code,
		&i.Name,
		&i.PriceIdr,
		&i.StockTotal,
		&i.StockLeft,
	)
	return i, err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO product (catalog_post_id, code, name, price_idr, stock_total, stock_left)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (catalog_post_id, code) DO UPDATE SET
    name      = EXCLUDED.name,
    price_idr = EXCLUDED.price_idr
RETURNING id, catalog_post_id, code, name, price_idr, stock_total, stock_left
`

type UpsertProductParams struct {
	CatalogPostID pgtype.UUID `json:"catalog_post_id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	PriceIdr      int64       `json:"price_idr"`
	StockTotal    int32       `json:"stock_total"`
}

// Idempotent registration of a keep/C product (used by cmd/seed). On
// conflict only identity fields (name/price) are refreshed — stock is left
// untouched so re-seeding doesn't reset stock consumed by prior test runs.
func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.CatalogPostID,
		arg.Code,
		arg.Name,
		arg.PriceIdr,
		arg.StockTotal,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CatalogPostID,
		&i.Code,
		&i.Name,
		&i.PriceIdr,
		&i.StockTotal,
		&i.StockLeft,
	)
	return i, err
}
