// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one

INSERT INTO reservation (
    account_id,
    catalog_post_id,
    product_id,
    code,
    ig_comment_id,
    contact_ig_user_id,
    contact_handle,
    hold_seconds,
    expires_at,
    wa_link
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, account_id, catalog_post_id, product_id, code, ig_comment_id, contact_ig_user_id, contact_handle, status, hold_seconds, reserved_at, expires_at, closed_at, wa_link
`

type CreateReservationParams struct {
	AccountID       pgtype.UUID        `json:"account_id"`
	CatalogPostID   pgtype.UUID        `json:"catalog_post_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Code            string             `json:"code"`
	IgCommentID     string             `json:"ig_comment_id"`
	ContactIgUserID string             `json:"contact_ig_user_id"`
	ContactHandle   string             `json:"contact_handle"`
	HoldSeconds     int32              `json:"hold_seconds"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	WaLink          string             `json:"wa_link"`
}

// Reservation CRUD + state machine queries (ADR-001 §2).
// Guard: UpdateReservationStatus uses WHERE status = @expected_status to prevent
// lost-update races when multiple workers process the same reservation concurrently.
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.AccountID,
		arg.CatalogPostID,
		arg.ProductID,
		arg.Code,
		arg.IgCommentID,
		arg.ContactIgUserID,
		arg.ContactHandle,
		arg.HoldSeconds,
		arg.ExpiresAt,
		arg.WaLink,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CatalogPostID,
		&i.ProductID,
		&i.Code,
		&i.IgCommentID,
		&i.ContactIgUserID,
		&i.ContactHandle,
		&i.Status,
		&i.HoldSeconds,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.WaLink,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, account_id, catalog_post_id, product_id, code, ig_comment_id, contact_ig_user_id, contact_handle, status, hold_seconds, reserved_at, expires_at, closed_at, wa_link FROM reservation WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CatalogPostID,
		&i.ProductID,
		&i.Code,
		&i.IgCommentID,
		&i.ContactIgUserID,
		&i.ContactHandle,
		&i.Status,
		&i.HoldSeconds,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.WaLink,
	)
	return i, err
}

const listExpiredActiveReservations = `-- name: ListExpiredActiveReservations :many
SELECT id FROM reservation
WHERE status IN ('reserved', 'waiting-pay')
  AND expires_at < now()
ORDER BY expires_at
LIMIT $1
`

// Backstop sweep (MAJOR-3b): active reservations already past expiry, for the
// reservation:reconcile task. Uses the partial index reservation_active_expires_at_idx.
func (q *Queries) ListExpiredActiveReservations(ctx context.Context, lim int32) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveReservations, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByAccount = `-- name: ListReservationsByAccount :many
SELECT id, account_id, catalog_post_id, product_id, code, ig_comment_id, contact_ig_user_id, contact_handle, status, hold_seconds, reserved_at, expires_at, closed_at, wa_link FROM reservation
WHERE account_id = $1
ORDER BY reserved_at DESC
LIMIT $3
OFFSET $2
`

type ListReservationsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

func (q *Queries) ListReservationsByAccount(ctx context.Context, arg ListReservationsByAccountParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByAccount, arg.AccountID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CatalogPostID,
			&i.ProductID,
			&i.Code,
			&i.IgCommentID,
			&i.ContactIgUserID,
			&i.ContactHandle,
			&i.Status,
			&i.HoldSeconds,
			&i.ReservedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.WaLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByPost = `-- name: ListReservationsByPost :many
SELECT id, account_id, catalog_post_id, product_id, code, ig_comment_id, contact_ig_user_id, contact_handle, status, hold_seconds, reserved_at, expires_at, closed_at, wa_link FROM reservation
WHERE catalog_post_id = $1
ORDER BY reserved_at DESC
`

func (q *Queries) ListReservationsByPost(ctx context.Context, catalogPostID pgtype.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByPost, catalogPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CatalogPostID,
			&i.ProductID,
			&i.Code,
			&i.IgCommentID,
			&i.ContactIgUserID,
			&i.ContactHandle,
			&i.Status,
			&i.HoldSeconds,
			&i.ReservedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.WaLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservation
SET
    status    = $1::reservation_status,
    closed_at = $2
WHERE id     = $3
  AND status = $4::reservation_status
RETURNING id, account_id, catalog_post_id, product_id, code, ig_comment_id, contact_ig_user_id, contact_handle, status, hold_seconds, reserved_at, expires_at, closed_at, wa_link
`

type UpdateReservationStatusParams struct {
	NewStatus      ReservationStatus  `json:"new_status"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	ID             pgtype.UUID        `json:"id"`
	ExpectedStatus ReservationStatus  `json:"expected_status"`
}

// Race guard: only transitions from the expected non-terminal state succeed.
// Caller passes closed_at = now() for terminal states (closed-wa, expired-released),
// nil for active transitions (reserved → waiting-pay).
func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus,
		arg.NewStatus,
		arg.ClosedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CatalogPostID,
		&i.ProductID,
		&i.Code,
		&i.IgCommentID,
		&i.ContactIgUserID,
		&i.ContactHandle,
		&i.Status,
		&i.HoldSeconds,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.WaLink,
	)
	return i, err
}
