// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO user_session (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// user_session queries backing RequireUser (ADR-003 §2.3/§3). Only the
// token_hash (SHA-256 of the raw cookie value) ever touches Postgres.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_session WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_session WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.password_hash, u.segment, u.onboarding_completed_at, u.created_at FROM user_session s
JOIN app_user u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

// Session lookup for RequireUser: token_hash -> user (join), rejecting expired sessions.
func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Segment,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
