// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWorkflow = `-- name: ActivateWorkflow :one
UPDATE workflow
SET status = 'live',
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND account_id = $2
RETURNING id, account_id, name, status, segment, version, created_at, updated_at
`

type ActivateWorkflowParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
}

// Publish: status -> 'live' and version bumped (cache-bust + run_log snapshot, §2.1).
func (q *Queries) ActivateWorkflow(ctx context.Context, arg ActivateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, activateWorkflow, arg.ID, arg.AccountID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Status,
		&i.Segment,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one

INSERT INTO workflow (account_id, name, segment)
VALUES ($1, $2, $3)
RETURNING id, account_id, name, status, segment, version, created_at, updated_at
`

type CreateWorkflowParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Name      string      `json:"name"`
	Segment   string      `json:"segment"`
}

// Workflow persistence queries (ADR-004 §2/§3). Scoping is always by
// account_id in addition to id so a guessed workflow id from another account
// can never be read/mutated (no separate authorization check needed in the
// handler beyond resolving the caller's own account_id).
func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow, arg.AccountID, arg.Name, arg.Segment)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Status,
		&i.Segment,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEdgesByWorkflow = `-- name: DeleteEdgesByWorkflow :exec
DELETE FROM workflow_edge WHERE workflow_id = $1
`

func (q *Queries) DeleteEdgesByWorkflow(ctx context.Context, workflowID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdgesByWorkflow, workflowID)
	return err
}

const deleteNodesByWorkflow = `-- name: DeleteNodesByWorkflow :exec
DELETE FROM workflow_node WHERE workflow_id = $1
`

// Cascades to workflow_edge via FK ON DELETE CASCADE; DeleteEdgesByWorkflow is
// called first by the store regardless, so ordering here is not load-bearing.
func (q *Queries) DeleteNodesByWorkflow(ctx context.Context, workflowID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNodesByWorkflow, workflowID)
	return err
}

const deleteWorkflow = `-- name: DeleteWorkflow :execrows
DELETE FROM workflow WHERE id = $1 AND account_id = $2
`

type DeleteWorkflowParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflow, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, account_id, name, status, segment, version, created_at, updated_at FROM workflow WHERE id = $1 AND account_id = $2
`

type GetWorkflowByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, arg.ID, arg.AccountID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Status,
		&i.Segment,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEdge = `-- name: InsertEdge :one
INSERT INTO workflow_edge (workflow_id, from_node_id, to_node_id)
VALUES ($1, $2, $3)
RETURNING id, workflow_id, from_node_id, to_node_id
`

type InsertEdgeParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	FromNodeID pgtype.UUID `json:"from_node_id"`
	ToNodeID   pgtype.UUID `json:"to_node_id"`
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) (WorkflowEdge, error) {
	row := q.db.QueryRow(ctx, insertEdge, arg.WorkflowID, arg.FromNodeID, arg.ToNodeID)
	var i WorkflowEdge
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.FromNodeID,
		&i.ToNodeID,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :one
INSERT INTO workflow_node (workflow_id, category, node_type, config, position_x, position_y)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workflow_id, category, node_type, config, position_x, position_y, created_at
`

type InsertNodeParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Category   string      `json:"category"`
	NodeType   string      `json:"node_type"`
	Config     []byte      `json:"config"`
	PositionX  int32       `json:"position_x"`
	PositionY  int32       `json:"position_y"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) (WorkflowNode, error) {
	row := q.db.QueryRow(ctx, insertNode,
		arg.WorkflowID,
		arg.Category,
		arg.NodeType,
		arg.Config,
		arg.PositionX,
		arg.PositionY,
	)
	var i WorkflowNode
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Category,
		&i.NodeType,
		&i.Config,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO workflow_run (
    workflow_id, workflow_name, account_id, trigger_source, trigger_summary,
    object_id, status, triggered, filter_passed, steps, error, duration_ms
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, workflow_id, workflow_name, account_id, trigger_source, trigger_summary, object_id, status, triggered, filter_passed, steps, error, duration_ms, created_at
`

type InsertRunParams struct {
	WorkflowID     pgtype.UUID `json:"workflow_id"`
	WorkflowName   string      `json:"workflow_name"`
	AccountID      pgtype.UUID `json:"account_id"`
	TriggerSource  string      `json:"trigger_source"`
	TriggerSummary string      `json:"trigger_summary"`
	ObjectID       string      `json:"object_id"`
	Status         string      `json:"status"`
	Triggered      bool        `json:"triggered"`
	FilterPassed   bool        `json:"filter_passed"`
	Steps          []byte      `json:"steps"`
	Error          string      `json:"error"`
	DurationMs     int32       `json:"duration_ms"`
}

// workflow_id is nullable (sqlc.narg): the transitional fallback built-in
// comment-to-order workflow (ADR-004 R3) has no persisted workflow row.
func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.WorkflowID,
		arg.WorkflowName,
		arg.AccountID,
		arg.TriggerSource,
		arg.TriggerSummary,
		arg.ObjectID,
		arg.Status,
		arg.Triggered,
		arg.FilterPassed,
		arg.Steps,
		arg.Error,
		arg.DurationMs,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowName,
		&i.AccountID,
		&i.TriggerSource,
		&i.TriggerSummary,
		&i.ObjectID,
		&i.Status,
		&i.Triggered,
		&i.FilterPassed,
		&i.Steps,
		&i.Error,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const listEdgesByWorkflow = `-- name: ListEdgesByWorkflow :many
SELECT id, workflow_id, from_node_id, to_node_id FROM workflow_edge WHERE workflow_id = $1
`

func (q *Queries) ListEdgesByWorkflow(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowEdge{}
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.FromNodeID,
			&i.ToNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveWorkflowsByAccount = `-- name: ListLiveWorkflowsByAccount :many
SELECT id, account_id, name, status, segment, version, created_at, updated_at FROM workflow
WHERE account_id = $1 AND status = 'live'
ORDER BY created_at ASC
`

// Loader hot-path (ADR-004 §1): only 'live' workflows are compiled per event.
func (q *Queries) ListLiveWorkflowsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listLiveWorkflowsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Status,
			&i.Segment,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByWorkflow = `-- name: ListNodesByWorkflow :many
SELECT id, workflow_id, category, node_type, config, position_x, position_y, created_at FROM workflow_node
WHERE workflow_id = $1
ORDER BY position_x ASC, created_at ASC
`

func (q *Queries) ListNodesByWorkflow(ctx context.Context, workflowID pgtype.UUID) ([]WorkflowNode, error) {
	rows, err := q.db.Query(ctx, listNodesByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowNode{}
	for rows.Next() {
		var i WorkflowNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Category,
			&i.NodeType,
			&i.Config,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByAccount = `-- name: ListRunsByAccount :many
SELECT id, workflow_id, workflow_name, account_id, trigger_source, trigger_summary, object_id, status, triggered, filter_passed, steps, error, duration_ms, created_at FROM workflow_run
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRunsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Lim       int32       `json:"lim"`
}

func (q *Queries) ListRunsByAccount(ctx context.Context, arg ListRunsByAccountParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listRunsByAccount, arg.AccountID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.AccountID,
			&i.TriggerSource,
			&i.TriggerSummary,
			&i.ObjectID,
			&i.Status,
			&i.Triggered,
			&i.FilterPassed,
			&i.Steps,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByWorkflow = `-- name: ListRunsByWorkflow :many
SELECT id, workflow_id, workflow_name, account_id, trigger_source, trigger_summary, object_id, status, triggered, filter_passed, steps, error, duration_ms, created_at FROM workflow_run
WHERE workflow_id = $1 AND account_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListRunsByWorkflowParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	AccountID  pgtype.UUID `json:"account_id"`
	Lim        int32       `json:"lim"`
}

func (q *Queries) ListRunsByWorkflow(ctx context.Context, arg ListRunsByWorkflowParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listRunsByWorkflow, arg.WorkflowID, arg.AccountID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.AccountID,
			&i.TriggerSource,
			&i.TriggerSummary,
			&i.ObjectID,
			&i.Status,
			&i.Triggered,
			&i.FilterPassed,
			&i.Steps,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByAccount = `-- name: ListWorkflowsByAccount :many
SELECT w.id, w.account_id, w.name, w.status, w.segment, w.version, w.created_at, w.updated_at, COUNT(n.id)::int AS node_count
FROM workflow w
LEFT JOIN workflow_node n ON n.workflow_id = w.id
WHERE w.account_id = $1
GROUP BY w.id
ORDER BY w.updated_at DESC
`

type ListWorkflowsByAccountRow struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Name      string             `json:"name"`
	Status    WorkflowStatus     `json:"status"`
	Segment   string             `json:"segment"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	NodeCount int32              `json:"node_count"`
}

// node_count powers the WorkflowSummary DTO without a second round-trip per row.
func (q *Queries) ListWorkflowsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListWorkflowsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowsByAccountRow{}
	for rows.Next() {
		var i ListWorkflowsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Status,
			&i.Segment,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkflowStatus = `-- name: SetWorkflowStatus :one
UPDATE workflow
SET status = $1::workflow_status,
    updated_at = now()
WHERE id = $2 AND account_id = $3
RETURNING id, account_id, name, status, segment, version, created_at, updated_at
`

type SetWorkflowStatusParams struct {
	Status    WorkflowStatus `json:"status"`
	ID        pgtype.UUID    `json:"id"`
	AccountID pgtype.UUID    `json:"account_id"`
}

// Generic status transition (pause -> 'paused', or marking 'error'). Does not
// bump version — only ActivateWorkflow does, since only publish needs cache-busting.
func (q *Queries) SetWorkflowStatus(ctx context.Context, arg SetWorkflowStatusParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, setWorkflowStatus, arg.Status, arg.ID, arg.AccountID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Status,
		&i.Segment,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowMeta = `-- name: UpdateWorkflowMeta :one
UPDATE workflow
SET name = $1,
    updated_at = now()
WHERE id = $2 AND account_id = $3
RETURNING id, account_id, name, status, segment, version, created_at, updated_at
`

type UpdateWorkflowMetaParams struct {
	Name      string      `json:"name"`
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
}

// Save draft (PUT): renames the workflow and bumps updated_at. version is
// intentionally NOT bumped here — version only bumps on activate (§2.1 comment).
func (q *Queries) UpdateWorkflowMeta(ctx context.Context, arg UpdateWorkflowMetaParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflowMeta, arg.Name, arg.ID, arg.AccountID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Status,
		&i.Segment,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
